trigger: none
pool : testingpool
stages:
  - stage: terraforminstall
    displayName: install
    jobs:
      - job: install
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
  - stage: terraforminit
    displayName: inint
    jobs:
      - job: inint
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/environment/dev'
            backendServiceArm: 'sc-azure-dev'
            backendAzureRmStorageAccountName: 'omkarstor1'
            backendAzureRmContainerName: 'omkarstorc'
            backendAzureRmKey: 'dev.terraform.state'
        