trigger: none
pool: wiproagent
stages:
 - stage: terraforminstall
   displayName: TerraformInstall
   jobs:
   - job: install
     steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'
 - stage: terraforminit
   displayName: TerraformInit
   jobs:
    - job: init
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)environment/dev'
          backendServiceArm: 'sc-azure-dev'
          backendAzureRmStorageAccountName: 'omkarstor1'
          backendAzureRmContainerName: 'omkarstorc'
          backendAzureRmKey: 'omkar.terrform.tfstate'

  


