trigger: none
pool : testingpool
stages:
  - stage: terraforminit
    displayName: install
    jobs:
      - job: install
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        