trigger: none
pool: wiproagent
stages:
 - stage: terraforminstall
   displayName: TerraformInstall
   jobs:
   - job: install
     steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'

  


