trigger: none
pool : testingpool
stages:
  - stage: cmd
    displayName: cmd
    jobs:
      - job: om
        steps:
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'Write-Host "Hello World"'
        